                                                                                                                                                                                                                                                                    format                                                                                                                                                                                                                                                                    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('company_name', 'MaxMule''s', 'text', 'Company name displayed on receipts and reports', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('currency_code', 'USD', 'text', 'ISO currency code', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('currency_symbol', '$', 'text', 'Currency symbol for displaying prices', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('date_format', 'MM/DD/YYYY', 'text', 'Date format for display', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('enable_multi_location', 'true', 'text', 'Enable multi-location support', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('enable_work_orders', 'true', 'text', 'Enable work order management system', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('session_timeout_minutes', '30', 'text', 'Session timeout in minutes', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('time_format', '12h', 'text', 'Time format (12h or 24h)', 'general', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('enrollment_journal_subtype_id', '0lSKj000000hcL3MAI', 'text', '', 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('journal_subtype_id', '0lSKj000000hnSJMAY', 'text', 'Selected journal subtype ID for MuleSoft integration', 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('journal_type_id', '0lEKj000000V4tLMAS', 'text', 'Selected journal type ID for MuleSoft integration', 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('loyalty_program_id', '0lpKj000000PzpFIAS', 'text', 'Selected loyalty program ID for MuleSoft integration', 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('mulesoft_loyalty_sync_endpoint', 'https://maxmules-loyalty-sync-w4i20p.5sc6y6-2.usa-e2.cloudhub.io', 'text', 'MuleSoft Loyalty Sync API endpoint URL', 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('sf_api_key', 'asdlfjherlkgncvs4xxz', 'text', NULL, 'integration', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('auto_generate_sku', 'true', 'text', 'Automatically generate SKUs for new products', 'inventory', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('low_stock_threshold', '5', 'text', 'Stock level to trigger low stock warning', 'inventory', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('landing_subtitle', 'Manage your entire business with our integrated Point of Sale and Customer Loyalty system. Streamline operations, boost sales, and reward your customers all in one place.', 'text', 'Subtitle/description text on landing page', 'landing_page', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('landing_system_name', 'POS & Loyalty System', 'text', 'System name displayed in header next to logo', 'landing_page', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('landing_title1', 'Complete Business Solution', 'text', 'Main title (first line) on landing page', 'landing_page', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('landing_title2', 'POS & Loyalty Platform', 'text', 'Secondary title (second line with gradient) on landing page', 'landing_page', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('points_per_dollar', '1', 'text', 'Loyalty points earned per dollar spent', 'loyalty', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('points_redemption_rate', '100', 'text', 'Points needed for $1 discount', 'loyalty', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('require_customer_email', 'false', 'text', 'Require email for new customers', 'loyalty', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('default_tax_rate', '0.08', 'text', 'Default tax rate for new locations', 'pos', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('enable_barcode_scanning', 'false', 'text', 'Enable barcode scanning support', 'pos', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('max_discount_percentage', '50', 'text', 'Maximum discount percentage allowed', 'pos', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('receipt_footer_text', 'Thank you for your business!', 'text', 'Text shown at bottom of receipts', 'pos', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('tax_inclusive', 'false', 'text', 'Whether prices include tax', 'pos', false, true, 'admin', 'admin') ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_delivery_fee', '5.00', 'text', 'Delivery fee amount', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_estimated_prep_time', '30', 'text', 'Estimated preparation time in minutes', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_free_delivery_threshold', '50.00', 'text', 'Free delivery over this amount', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_hero_enabled', 'true', 'text', 'Show hero/banner section on shop page', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_hero_subtitle', 'Fresh, delicious, delivered to your door', 'text', 'Hero section subtitle', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_hero_title', 'Order Your Favorites', 'text', 'Hero section title', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
 INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_encrypted, is_active, created_by, updated_by) VALUES ('shop_min_order_amount', '0', 'text', 'Minimum order amount (0 for no minimum)', 'shop', false, true, NULL, NULL) ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
(35 rows)

                                                                                                                                                                                                                                                                                                                     format                                                                                                                                                                                                                                                                                                                      
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('admin', 'Full system access with all permissions', '{"pos": {"read": true, "write": true, "delete": true}, "users": {"read": true, "write": true, "delete": true}, "reports": {"read": true, "write": true}, "settings": {"read": true, "write": true, "delete": true}, "customers": {"read": true, "write": true, "delete": true}, "inventory": {"read": true, "write": true, "delete": true}, "locations": {"read": true, "write": true, "delete": true}, "transactions": {"read": true, "write": true, "delete": true}}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('Admin', 'System Administrator', '{"all": true}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('cashier', 'Basic POS operations and customer service', '{"pos": {"read": true, "write": true}, "users": {"read": true}, "reports": {"read": true}, "settings": {"read": true}, "customers": {"read": true, "write": true}, "inventory": {"read": true}, "locations": {"read": true}, "transactions": {"read": true, "write": true}}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('Customer', 'Customer', '{"orders": true, "profile": true}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('Employee', 'Store Employee', '{"pos": true, "inventory": true}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('manager', 'Store management with limited admin access', '{"pos": {"read": true, "write": true}, "users": {"read": true}, "reports": {"read": true, "write": true}, "settings": {"read": true}, "customers": {"read": true, "write": true}, "inventory": {"read": true, "write": true}, "locations": {"read": true, "write": true}, "transactions": {"read": true, "write": true}}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('Manager', 'Store Manager', '{"store": true, "reports": true}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
 INSERT INTO roles (name, description, permissions, is_active) VALUES ('viewer', 'Read-only access for reporting and monitoring', '{"pos": {"read": true}, "users": {"read": true}, "reports": {"read": true}, "settings": {"read": true}, "customers": {"read": true}, "inventory": {"read": true}, "locations": {"read": true}, "transactions": {"read": true}}'::jsonb, true) ON CONFLICT (name) DO NOTHING;
(8 rows)

                                                                                                                                                      format                                                                                                                                                      
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('Credit Card', 'credit_card', 'Pay online with credit or debit card', true, 1, '/loyalty/payment-methods/credit-card.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('Cash on Delivery', 'cash', 'Pay with cash when order arrives', false, 2, '/loyalty/payment-methods/cash.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('Pay at Pickup', 'pay_at_pickup', 'Pay when you pick up your order', false, 3, '/loyalty/payment-methods/pay-at-pickup.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('Apple Pay', 'apple_pay', 'Pay with Apple Pay', true, 4, '/loyalty/payment-methods/apple-pay.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('PayPal', 'paypal', 'Pay securely with PayPal', true, 5, '/loyalty/payment-methods/paypal.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
 INSERT INTO payment_methods (name, code, description, requires_online_payment, display_order, icon, is_active) VALUES ('Google Pay', 'google_pay', 'Pay with Google Pay', true, 5, '/loyalty/payment-methods/google.png', true) ON CONFLICT (code) DO UPDATE SET icon = EXCLUDED.icon;
(6 rows)

